export const periwinkle = "#CAE5FF"
export const freshAir = "#ACEDFF"
export const jordyBlue = "#89BBFE"
export const silverLakeBlue = "#6F8AB7"
export const graniteGray = "#615D6C"
export const darkerBlue = "#42638E"

export const smoke = "#F5F5F5"
export const offWhite = "#FAF9F6"
export const navajo = "#F9F6EE"
export const strongrange = "#FF5733"
